# Generated by Django 5.1.5 on 2025-01-26 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Newsdesk", "0003_alter_newspaper_publishers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newspaper",
            options={"verbose_name": "newspaper"},
        ),
        migrations.AlterModelOptions(
            name="redactor",
            options={"verbose_name": "redactor"},
        ),
        migrations.AlterModelOptions(
            name="topic",
            options={"verbose_name": "topic"},
        ),
    ]
